blog/urls.py
from django.urls import re_path, path

from . import views


app_name = "blog"
urlpatterns = [
    re_path(r'^$', views.post_list, name='post_list'),
    re_path(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    re_path(r'^post/new/$', views.post_new, name='post_new'),
    re_path(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    re_path(r'^draft/$', views.post_draft_list, name='post_draft_list'),
    re_path(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    re_path(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    path('by/<username>', views.ListUserPost.as_view(), name='user_post'),
    path('search', views.SearchView.as_view(), name='search'),
]

mysite/urls.py
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/login/$', views.login, name='login'),
    re_path(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/blog/'}),
    re_path(r'^blog/', include('blog.urls')),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
# class Category(models.Model):
#     tag = models.CharField(max_length=100)

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
    viewed = models.IntegerField(default=0, editable=0)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from . import models
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404
# CBV below
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def post_list(request):
    posts = models.Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


class SearchView(ListView):
    template_name = "blog/post_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        search_term = self.request.GET.get("term")
        posts = models.Post.objects.filter(
            Q(published_date__lte=timezone.now()),
            Q(title__icontains=search_term) | Q(text__icontains=search_term)
        ).order_by('-published_date')
        return posts


@login_required
def post_draft_list(request):
    posts = models.Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


@login_required
def post_publish(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


def post_detail(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_remove(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')


# CBV below


class ListUserPost(LoginRequiredMixin, ListView):
    template_name = "blog/user_post_list.html"

    def get_queryset(self):
        """
        Without select_related or prefetch related:
            7 SQL queries, takes 3.99 ms
        With prefetch_related
            8 SQL queries, takes 0.5 ms
        With select_related
            5 SQL queries, takes 15.66 ms

        Not very sure if it is necessary to use these techniques.
        """
        username = self.kwargs.get("username")
        # try:
        #     posts = models.Post.objects.select_related('author').filter(author__username=username)
        # except models.Post.DoesNotExist:
        #     raise Http404
        # else:
        #     return posts

        posts = models.Post.objects.filter(author__username=username)
        return posts

blog/templates/blog/base.html
{% load staticfiles %}
<html>
<head>
  <title>Kool Blog</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
        integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Modak" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
        integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

</head>
<body>

<div class="page-header">

  <form class="top-menu" class="form-inline" method="get" name="searchform" action="{% url 'blog:search' %}">

      <input class="form-control form-control-sm" type="text"
             name="term" placeholder="key word">
      <button type="submit" class="btn btn-outline-primary">Search</button>

  </form>

  {% if user.is_authenticated %}
    <a href="{% url 'blog:user_post' username=user.username %}" class="top-menu">
      <i class="far fa-address-card"></i></a>
    <a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-plus"></i></a>
    <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><i class="far fa-edit"></i></a>
    <p class="top-menu">Hello {{ user.username }}
      <small>(<a href="{% url 'logout' %}">Logout</a>)</small>
    </p>
  {% else %}
    <a href="{% url 'login' %}" class="top-menu"><i class="fas fa-user-lock"></i>Log in</a>
  {% endif %}


  <h1><a href="/blog/">It's a Kool School Blog</a></h1>
</div>
<div class="content container">
  <div class="row">
    <div class="col-md-8">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><i class="fas fa-pencil-alt"></i></a>
            <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><i class="far fa-trash-alt"></i></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }} (Not yet published)</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>New post</h1>
    <form method="POST" class="post-form"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <h1><a href="{%  url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <div class="date">
                <p>Published: {{ post.published_date }} Word Count ({{ post.text|wordcount }})</p>
            </div>

            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/user_post_list.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="card">
    <div class="card-header">
      The author ({{ object_list.0.author.first_name }} {{ object_list.0.author.last_name }})
      has published {{ object_list|length }} posts.
    </div>
    <ul class="list-group list-group-flush">
    {% for post in object_list %}
      <a href="{% url 'blog:post_detail' pk=post.pk %}">
        <li class="list-group-item">{{ post.title }}</li>
      </a>
    {% empty %}
        nothing
    {% endfor %}
    </ul>
  </div>
{% endblock content %}